### ISSUE TITLE
RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)

### ISSUE THREAD

**Issue by bizintelligence** [MicrosoftLearning/AI-SpeechToText#1]
Hi,

I am trying to complete the "Exercise - Convert Speech from an Audio File to Text" in learning module "Translate speech in real time with Azure Cognitive Services". I download the sample from to local windows machine. My machine is configured with Visual Studio Code and python virtual environment (3.7) with required packages. Everytime, I run this file in terminal I get following error/info:

Traceback (most recent call last):
  File "c:/local/GitHub/AI-SpeechToText-master/speechtotext.py", line 14, in <module>
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_input)
  File "C:\local\Anaconda3\envs\azure\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 761, in __init__ 
    self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config)
  File "C:\local\Anaconda3\envs\azure\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 547, in _get_impl
    _impl = reco_type._from_config(speech_config._impl, audio_config._impl)
RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
[CALL STACK BEGIN]

    > file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - file_logger_stop_logging

    - recognizer_stop_keyword_recognition_async_wait_for

    - recognizer_create_speech_recognizer_from_config

    - 00007FFF53D98A8D (SymFromAddr() error: Attempt to access invalid address.)

    - PyInit__speech_py_impl

    - 00007FFF53D39CEE (SymFromAddr() error: Attempt to access invalid address.)

    - PyMethodDef_RawFastCallKeywords

    - PyMethodDef_RawFastCallKeywords

    - PyEval_EvalFrameDefault

[CALL STACK END]

*******************************************************************************
Can you please help?

Thanks

**Comment by gerryaobrien** [comment]
Currently investigating.  I tested the online environment, as in the lab instructions, and it works fine.  I created an offline version locally, and I get the same error you do.  

Will update this repo when I discover the issue.  In the meantime, use the VS Code online environment if this is blocking you.

**Comment by gerryaobrien** [comment]
Ok, this error is generated because it cannot find the file.  You can use relative or absolute paths, or move the narration.wav file to the root folder of the repo.
